package ink.rubi.danmu

enum class Version(val version: Short) {
    WS_BODY_PROTOCOL_VERSION_NORMAL(0),
    WS_BODY_PROTOCOL_VERSION_INT(1), // 用于心跳包
    WS_BODY_PROTOCOL_VERSION_DEFLATE(2)
}
enum class Operation(val code: Int) {
    HANDSHAKE(0),
    HANDSHAKE_REPLY(1),
    HEARTBEAT(2),
    HEARTBEAT_REPLY(3),
    SEND_MSG(4),
    SEND_MSG_REPLY(5),
    DISCONNECT_REPLY(6),
    AUTH(7),
    AUTH_REPLY(8),
    RAW(9),
    PROTO_READY(10),
    PROTO_FINISH(11),
    CHANGE_ROOM(12),
    CHANGE_ROOM_REPLY(13),
    REGISTER(14),
    REGISTER_REPLY(15),
    UNREGISTER(16),
    UNREGISTER_REPLY(17),
}

enum class CMD(val desc:String){
    DANMU_MSG("收到弹幕"),
    ROOM_REAL_TIME_MESSAGE_UPDATE("?"),
    SEND_GIFT("有人送礼"),
    SUPER_CHAT_MESSAGE("醒目留言"),
    SUPER_CHAT_MESSAGE_DELETE("删除醒目留言"),
    GUARD_BUY("有人上舰"),
//    'ACTIVITY_BANNER_RED_NOTICE_CLOSE',
//    'ACTIVITY_BANNER_UPDATE_V2',
//    'ACTIVITY_MATCH_GIFT',
//    'ACTIVITY_RED_PACKET',
//    'BLOCK',
//    'CHANGE_ROOM_INFO',
//    'CLOSE',
//    'COMBO_END',
//    'COMBO_SEND',
//    'CUT_OFF',
//    'DAILY_QUEST_NEWDAY',
//    'END',
//    'ENTRY_EFFECT',
//    'GUARD_LOTTERY_START',
//    'GUARD_MSG',
//    'GUIARD_MSG',
//    'HOUR_RANK_AWARDS',
//    'LIVE',
//    'LOL_ACTIVITY',
//    'LUCK_GIFT_AWARD_USER',
//    'MESSAGEBOX_USER_GAIN_MEDAL',
//    'new_anchor_reward',
//    'NOTICE_MSG',
//    'PK_AGAIN',
//    'PK_END',
//    'PK_MATCH',
//    'PK_MIC_END',
//    'PK_PRE',
//    'PK_PROCESS',
//    'PK_SETTLE',
//    'PK_START',
//    'PREPARING',
//    'RAFFLE_END',
//    'RAFFLE_START',
//    'REFRESH',
//    'ROOM_ADMINS',
//    'room_admin_entrance',
//    'ROOM_BLOCK_INTO',
//    'ROOM_BLOCK_MSG',
//    'ROOM_BOX_MASTER',
//    'ROOM_CHANGE',
//    'ROOM_KICKOUT',
//    'ROOM_LIMIT',
//    'ROOM_LOCK',
//    'ROOM_RANK',
//    'ROOM_REAL_TIME_MESSAGE_UPDATE',
//    'ROOM_REAL_TIME_MESSAGE_UPDATE',
//    'ROOM_REFRESH',
//    'ROOM_SHIELD',
//    'ROOM_SILENT_OFF',
//    'ROOM_SILENT_ON',
//    'ROOM_SKIN_MSG',
//    'ROUND',
//    'SCORE_CARD',
//    'SEND_TOP',
//    'SPECIAL_GIFT',
//    'SUPER_CHAT_ENTRANCE',
//    'SUPER_CHAT_MESSAGE_JPN',
//    'SYS_GIFT',
//    'SYS_MSG',
//    'TV_END',
//    'TV_START',
//    'USER_TOAST_MSG',
//    'WARNING',
//    'WEEK_STAR_CLOCK',
    WELCOME("进入直播间"),
    WELCOME_GUARD("进入直播间"),
//    'WIN_ACTIVITY',
//    'WISH_BOTTLE'

}